/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.xtext.example.mydsl.ui.AbstractMyDslUiModule;
import org.xtext.example.mydsl.ui.MathExpressionHoverProvider;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MyDslUiModule extends AbstractMyDslUiModule {
  public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
    return MathExpressionHoverProvider.class;
  }
  
  public MyDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
