/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MyDslUiModule extends AbstractMyDslUiModule {
	def Class<? extends IEObjectHoverProvider>
 		bindIEObjectHoverProvider() {
		return MathExpressionHoverProvider
	}
}
