/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.generator.MyDslGenerator;
import org.xtext.example.mydsl.myDsl.MathExp;
import org.xtext.example.mydsl.tests.MyDslInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(MyDslInjectorProvider.class)
@SuppressWarnings("all")
public class MyDslParsingTest {
  @Inject
  private ParseHelper<MathExp> parseHelper;
  
  @Test
  public void T01_dummy() {
    Assertions.assertTrue(true);
  }
  
  @Test
  public void T01_loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 87");
      final MathExp result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T02_addition() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 80+7");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T02_addsub() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 100-20+10-3");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T02_muldiv() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 100*20/10*3");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 600);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T02_parens() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is (10+3)*7-4");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T03_precedence() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 10+3*4-12/3+3");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 21);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T03_left_assoc_minus() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 10-5-2");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 3);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T03_left_assoc_div() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is 10/5/2");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 1);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T04_let() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is let x=10*8 in x+7 end");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T04_nested_let_other_var() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is let x=2 in let y=3 in x*y end + x end + 79");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void T04_nested_let_same_var() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("result is let x=2 in let x=3 in x*x end + x end + 76");
      final MathExp result = this.parseHelper.parse(_builder);
      int _computeInt = MyDslGenerator.computeInt(result);
      boolean _equals = (_computeInt == 87);
      Assertions.assertTrue(_equals);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
